GRANT CREATE SESSION,
    CREATE TABLE,
    CREATE SEQUENCE,
    CREATE TYPE,
    CREATE TRIGGER,
    CREATE PROCEDURE, -- Covers Procedures, Functions, and Packages
    CREATE JOB
    TO CARPOOLING_APP_USER;
