GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, INDEX, REFERENCES
    ON CARPOOLING_DB.* TO 'CARPOOLING_APP_USER'@'localhost';

GRANT CREATE ROUTINE, ALTER ROUTINE, EXECUTE
    ON CARPOOLING_DB.* TO 'CARPOOLING_APP_USER'@'localhost';

GRANT TRIGGER
    ON CARPOOLING_DB.* TO 'CARPOOLING_APP_USER'@'localhost';

GRANT CREATE VIEW, SHOW VIEW
    ON CARPOOLING_DB.* TO 'CARPOOLING_APP_USER'@'localhost';

GRANT EVENT
    ON CARPOOLING_DB.* TO 'CARPOOLING_APP_USER'@'localhost';