-- Sequence for DailyReport Table
CREATE SEQUENCE SEQ_DAILYREPORT
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for Institution Table
CREATE SEQUENCE SEQ_INSTITUTION
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for ContactPhoneNumber Table
CREATE SEQUENCE SEQ_CONTACTPHONENUMBER
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for ContactEmail Table
CREATE SEQUENCE SEQ_CONTACTEMAIL
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for AccessStatus Table
CREATE SEQUENCE SEQ_ACCESSSTATUS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for Person Table
CREATE SEQUENCE SEQ_PERSON
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for PhoneNumber Table
CREATE SEQUENCE SEQ_PHONENUMBER
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for Email Table
CREATE SEQUENCE SEQ_EMAIL
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for Credential Table
CREATE SEQUENCE SEQ_CREDENTIAL
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for TypeOfCredential Table
CREATE SEQUENCE SEQ_TYPEOFCREDENTIAL
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for Gender Table
CREATE SEQUENCE SEQ_GENDER
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for PersonalUser Table
CREATE SEQUENCE SEQ_PERSONALUSER
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for UserStatus Table
CREATE SEQUENCE SEQ_USERSTATUS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for InstitutionalEmail Table
CREATE SEQUENCE SEQ_INSTITUTIONALEMAIL
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for Vehicle Table
CREATE SEQUENCE SEQ_VEHICLE
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for Trip Table
CREATE SEQUENCE SEQ_TRIP
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for PriceStatus Table
CREATE SEQUENCE SEQ_PRICESTATUS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for TripStatus Table
CREATE SEQUENCE SEQ_TRIPSTATUS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for Stop Table
CREATE SEQUENCE SEQ_STOP
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for CoordinateLocation Table
CREATE SEQUENCE SEQ_COORDINATELOCATION
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for District Table
CREATE SEQUENCE SEQ_DISTRICT
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for Canton Table
CREATE SEQUENCE SEQ_CANTON
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for Province Table
CREATE SEQUENCE SEQ_PROVINCE
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for Country Table
CREATE SEQUENCE SEQ_COUNTRY
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for PaymentMethod Table
CREATE SEQUENCE SEQ_PAYMENTMETHOD
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for AuditLog Table
CREATE SEQUENCE SEQ_AUDITLOG
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for Parameter Table
CREATE SEQUENCE SEQ_PARAMETER
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for LogBook Table
CREATE SEQUENCE SEQ_LOGBOOK
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for EntityModified Table
CREATE SEQUENCE SEQ_ENTITYMODIFIED
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Sequence for AttributeModified Table
CREATE SEQUENCE SEQ_ATTRIBUTEMODIFIED
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
